### ISSUE TITLE
Keepinventory

### ISSUE THREAD

**Issue by MasterKatrix** [cyanobacterium/DrCyanos_Lootable-Bodies#6] opened 2015-05-24 08:51 UTC
Did i use an old version, or does this mod don't work with the vanilla function keepInventory=?

**Comment by cyanobacterium** [comment] 2015-05-24 12:23
In version 1.3.3 (and later), I made it check the keepInventory game rule and the intended behavior is that if keepInventory=true, then no items are transferred from the player's inventory to the corpse. If that is not what you observe, then please provide a detailed description of what actually happens, what are the circumstances that you used to test this, whether keepInventory works when this mod is not installed, and whether the bug still persists when you remove all mods except Lootable Bodies. With that information, I should be able to track down any bug.

Also, make sure you are launching your server with just Forge and not a plugin-hosting launcher when you are testing for bugs. The plugin launchers tend to inject extra programming hooks which have been known to interfere with Lootable Bodies.

**Comment by cyanobacterium** [comment] 2015-06-08 11:59
Are you still having issues with Lootable Bodies or can I close this issue thread?

**Comment by cyanobacterium** [comment] 2015-06-19 12:17
Closed due to lack of response.

**Closed by cyanobacterium** 2015-06-19 12:17 UTC
